/** Texto del catálogo para el prompt (debe coincidir con códigos 0–36 del front y de tipoDiagnostico). */
export const CATALOGO_TIPOS_DIAGNOSTICO_PROMPT = `
0 = N/A
1 = Estudio Normal
2 = Hipertrofia Ventricular Izquierda
3 = Dilatacion Auricular Izquierda
4 = Patologia Aortica
5 = Aneurisma Aortico
6 = Aneurisma Ventricular Izquierdo
7 = Fibrosis/Calcificacion Valvular
8 = Disfuncion Sistolica VI
9 = Disfuncion Diastolica VI
10 = Disfuncion Sistolica VD
11 = Disfuncion Sistolica Biventricular
12 = Cardiopatia Isquemica
13 = Prolapso Mitral
14 = Insuficiencia Mitral
15 = Insuficiencia Aortica
16 = Estenosis Mitral
17 = Estenosis Aortica
18 = Protesis Aórtica
19 = Protesis Mitral
20 = Protesis Disfuncionante
21 = Miocardiopatia Hipertrofica Obstructiva
22 = Miocardiopatia Hipertrofica No Obstructiva
23 = Miocardiopatia Dilatada
24 = Cardiopatia Infiltrativa/Restrictiva
25 = Miocardiopatia Chagasica
26 = Cardiopatia Congenita
27 = CIA
28 = CIV
29 = Masa Cardiaca
30 = Mixoma Auricular
31 = Vegetacion Valvular
32 = Derrame Pericardico
33 = Pericarditis Constrictiva
34 = Hipertension Pulmonar
35 = Probable tromboembolismo Pulmonar
36 = Endocarditis Infecciosa
`.trim();
